export const INIT_STORE = 'INIT_STORE'

export const CHANGE_THEME = 'CHANGE_THEME'

export const SET_SNACKBAR_MESSAGE = 'SET_SNACKBAR_MESSAGE'

export const TOGGLE_LOGIN_STATUS = 'TOGGLE_LOGIN_STATUS'
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'
export const TOGGLE_FETCHING = 'TOGGLE_FETCHING'

export const LOGIN_URLS_REQUEST = 'LOGIN_URLS_REQUEST'
export const LOGIN_URLS_SUCCESS = 'LOGIN_URLS_SUCCESS'
export const LOGIN_URLS_FAILURE = 'LOGIN_URLS_FAILURE'

export const USER_ACCOUNT_REQUEST = 'USER_ACCOUNT_REQUEST'
export const USER_ACCOUNT_SUCCESS = 'USER_ACCOUNT_SUCCESS'
export const USER_ACCOUNT_FAILURE = 'USER_ACCOUNT_FAILURE'

export const ACCOUNTS_REQUEST = 'ACCOUNTS_REQUEST'
export const ACCOUNTS_SUCCESS = 'ACCOUNTS_SUCCESS'
export const ACCOUNTS_FAILURE = 'ACCOUNTS_FAILURE'

export const USERS_REQUEST = 'USERS_REQUEST'
export const USERS_SUCCESS = 'USERS_SUCCESS'
export const USERS_FAILURE = 'USERS_FAILURE'

export const PAGES_REQUEST = 'PAGES_REQUEST'
export const PAGES_SUCCESS = 'PAGES_SUCCESS'
export const PAGES_FAILURE = 'PAGES_FAILURE'

export const COUNTER_REQUEST = 'COUNTER_REQUEST'
export const COUNTER_SUCCESS = 'COUNTER_SUCCESS'
export const COUNTER_FAILURE = 'COUNTER_FAILURE'

export const DEMANDS_REQUEST = 'DEMANDS_REQUEST'
export const DEMANDS_SUCCESS = 'DEMANDS_SUCCESS'
export const DEMANDS_FAILURE = 'DEMANDS_FAILURE'

export const OFFERS_REQUEST = 'OFFERS_REQUEST'
export const OFFERS_SUCCESS = 'OFFERS_SUCCESS'
export const OFFERS_FAILURE = 'OFFERS_FAILURE'

export const SERVICE_PACKS_REQUEST = 'SERVICE_PACKS_REQUEST'
export const SERVICE_PACKS_SUCCESS = 'SERVICE_PACKS_SUCCESS'
export const SERVICE_PACKS_FAILURE = 'SERVICE_PACKS_FAILURE'

export const SIGN_OUT_URL_REQUEST = 'SIGN_OUT_URL_REQUEST'
export const SIGN_OUT_URL_SUCCESS = 'SIGN_OUT_URL_SUCCESS'
export const SIGN_OUT_URL_FAILURE = 'SIGN_OUT_URL_FAILURE'
