export const INIT_STORE = "INIT_STORE"

export const CHANGE_THEME = "CHANGE_THEME"

export const ROUTE_CONTENTS_SUCCESS = "ROUTE_CONTENTS_SUCCESS"
export const ROUTE_CONTENTS_RESET_ALL = "ROUTE_CONTENTS_RESET_ALL"

export const ADD_SNACKBAR = "ADD_SNACKBAR"
export const REMOVE_SNACKBAR = "REMOVE_SNACKBAR"

export const TOGGLE_LOGIN_STATUS = "TOGGLE_LOGIN_STATUS"
export const TOGGLE_DRAWER = "TOGGLE_DRAWER"
export const TOGGLE_FETCHING = "TOGGLE_FETCHING"

export const LOGIN_URLS_SUCCESS = "LOGIN_URLS_SUCCESS"

export const USER_LOGGED_SUCCESS = "USER_LOGGED_SUCCESS"

export const USER_TAGS_REQUEST = "USER_TAGS_REQUEST"
export const USER_TAGS_SUCCESS = "USER_TAGS_SUCCESS"
export const USER_TAGS_FAILURE = "USER_TAGS_FAILURE"
export const USER_TAGS_REMOVE = "USER_TAGS_REMOVE"

export const USER_ROLES_REQUEST = "USER_ROLES_REQUEST"
export const USER_ROLES_SUCCESS = "USER_ROLES_SUCCESS"
export const USER_ROLES_FAILURE = "USER_ROLES_FAILURE"
export const USER_ROLES_REMOVE = "USER_ROLES_REMOVE"

export const SIGN_OUT_URL_SUCCESS = "SIGN_OUT_URL_SUCCESS"

export const ACCOUNT_LOGGED_SUCCESS = "ACCOUNT_LOGGED_SUCCESS"

export const LANGUAGES_REQUEST = "LANGUAGES_REQUEST"
export const LANGUAGES_SUCCESS = "LANGUAGES_SUCCESS"
export const LANGUAGES_FAILURE = "LANGUAGES_FAILURE"
export const LANGUAGEIDS_SELECTED_ADD_REMOVE = "LANGUAGEIDS_SELECTED_ADD_REMOVE"

export const COUNTER_SUCCESS = "COUNTER_SUCCESS"

export const DEMANDS_REQUEST = "DEMANDS_REQUEST"
export const DEMANDS_SUCCESS = "DEMANDS_SUCCESS"
export const DEMANDS_FAILURE = "DEMANDS_FAILURE"
export const DEMAND_SUCCESS = "DEMAND_SUCCESS"

export const OFFERS_REQUEST = "OFFERS_REQUEST"
export const OFFERS_SUCCESS = "OFFERS_SUCCESS"
export const OFFERS_FAILURE = "OFFERS_FAILURE"
export const OFFER_SUCCESS = "OFFER_SUCCESS"

export const SERVICE_PACKS_REQUEST = "SERVICE_PACKS_REQUEST"
export const SERVICE_PACKS_SUCCESS = "SERVICE_PACKS_SUCCESS"
export const SERVICE_PACKS_FAILURE = "SERVICE_PACKS_FAILURE"
export const SERVICE_PACK_SUCCESS = "SERVICE_PACK_SUCCESS"

export const ACCOUNTS_REQUEST = "ACCOUNTS_REQUEST"
export const ACCOUNTS_SUCCESS = "ACCOUNTS_SUCCESS"
export const ACCOUNTS_FAILURE = "ACCOUNTS_FAILURE"
export const ACCOUNT_SUCCESS = "ACCOUNT_SUCCESS"

export const USERS_REQUEST = "USERS_REQUEST"
export const USERS_SUCCESS = "USERS_SUCCESS"
export const USERS_FAILURE = "USERS_FAILURE"
export const USERIDS_SELECTED_ADD_REMOVE = "USERIDS_SELECTED_ADD_REMOVE"
export const USER_SUCCESS = "USER_SUCCESS"

export const TAGS_REQUEST = "TAGS_REQUEST"
export const TAGS_SUCCESS = "TAGS_SUCCESS"
export const TAGS_FAILURE = "TAGS_FAILURE"
export const TAGIDS_SELECTED_BY_USER_SET = "TAGIDS_SELECTED_BY_USER_SET"
export const TAGIDS_SELECTED_BY_USER_REMOVE = "TAGIDS_SELECTED_BY_USER_REMOVE"

export const ROLES_REQUEST = "ROLES_REQUEST"
export const ROLES_SUCCESS = "ROLES_SUCCESS"
export const ROLES_FAILURE = "ROLES_FAILURE"
export const ROLEIDS_SELECTED_BY_USER_SET = "ROLEIDS_SELECTED_BY_USER_SET"
export const ROLEIDS_SELECTED_BY_USER_REMOVE = "ROLEIDS_SELECTED_BY_USER_REMOVE"

export const ROLETYPES_REQUEST = "ROLETYPES_REQUEST"
export const ROLETYPES_SUCCESS = "ROLETYPES_SUCCESS"
export const ROLETYPES_FAILURE = "ROLETYPES_FAILURE"
export const ROLETYPEIDS_SELECTED_RESET = "ROLETYPEIDS_SELECTED_RESET"

export const PAGES_REQUEST = "PAGES_REQUEST"
export const PAGES_SUCCESS = "PAGES_SUCCESS"
export const PAGES_FAILURE = "PAGES_FAILURE"
export const PAGEIDS_SELECTED_ADD_REMOVE = "PAGEIDS_SELECTED_ADD_REMOVE"
export const PAGE_SUCCESS = "PAGE_SUCCESS"

export const CONTENTS_REQUEST = "CONTENTS_REQUEST"
export const CONTENTS_SUCCESS = "CONTENTS_SUCCESS"
export const CONTENTS_FAILURE = "CONTENTS_FAILURE"
export const CONTENTIDS_SELECTED_ADD_REMOVE = "CONTENTIDS_SELECTED_ADD_REMOVE"

export const CONTENT_UPDATE = "CONTENT_UPDATE"
